### ISSUE TITLE
javascript 8.7.6

### ISSUE THREAD

**Issue by crunchip77** [Pittini/iobroker-Fensterauswertung#52]
mit dem upgrade nun folgende Meldung

`javascript.0	12:25:12.963	error	script.js.Benachrichtigung.FensterTür-Status: getObject has been called with id of type "function" but expects a string
javascript.0	12:25:12.965	error	script.js.Benachrichtigung.FensterTür-Status: TypeError: Cannot read properties of undefined (reading '0')
javascript.0	12:25:12.965	error	at script.js.Benachrichtigung.FensterTür-Status:154:77
javascript.0	12:25:12.965	error	at script.js.Benachrichtigung.FensterTür-Status:1468:3
`

**Comment by Pittini** [comment]
Ich hab grade auf die stable 8.8.3 upgedated und keine Fehler. Hat sich das bei Dir auch erledigt?

**Comment by crunchip77** [comment]
@Pittini leider nein, bin auch mittlerweile schon bei v8.9.1 und noch immer der selbe Fehler

**Comment by Pittini** [comment]
Dann geh ich davon aus dasses eher nicht am Skript an sich liegt, sonst hätt ich den FERhler auch und es würde schon von mehr Leuten gemeldet worden sein.
Cannot read properties of undefined (reading '0') Deutet eigentlich immer drauf hin dass entweder ein Gerät nimmer da ist, oder einen Nullwert irgendwo drin hat wo es nicht sein sollte. In meinem Batterieskript z.B. kommt son Fehler wenn ich ein neues Gerät einbinde dass aber noch keine Batterieinfo gesendet hat. Also evtl. mal alle Sensoren durchgehen. Oder das Logging aktivieren und schauen ob da was aussagekräftigeres rumkommt.

**Comment by crunchip77** [comment]
@Pittini es waren tatsächlich 2 Sensoren verschwunden, habe diese wieder eingebunden und auch nochmal alle durchgesehen. Javascript Instanz habe ich diesbezüglich auch neu gestartet Es sind überall Werte vorhanden, jedoch bleibt der Fehler.

**Comment by fzoellne** [comment]
Hallo,

ich habe diesen Fehler hier

`<head></head>
avascript.0 | 2025-03-23 17:29:29.194 | error | at Script.runInContext (node:vm:149:12)
-- | -- | -- | --
javascript.0 | 2025-03-23 17:29:29.193 | error | at script.js.Fenster_Türen.Fensterüberwachung:1468:3
javascript.0 | 2025-03-23 17:29:29.193 | error | at script.js.Fenster_Türen.Fensterüberwachung:154:67
javascript.0 | 2025-03-23 17:29:29.192 | error | script.js.Fenster_Türen.Fensterüberwachung: TypeError: Cannot read properties of null (reading 'enumNames')

`

davor kommt diese Warnung

`<head></head>
avascript.0 | 2025-03-23 17:29:29.158 | warn | script.js.Fenster_Türen.Fensterüberwachung: Object "zigbee.0.00124b002a4f70a6.opened" does not exist
-- | -- | -- | --


`

Wobei das Gerät gar nicht im Netz ist. 

Js Version 8.9.1

**Comment by Pittini** [comment]
@fzoellne : Wenn das Gerät nicht existiert, aber angemckert wird liegt vermutlich ne Leiche rum. Gugg mal unter Kategorien > Funktionen > Tuer, sowie Fenster (oder wie Du die genannt hast falls Du nicht dem Standard gefolgt bist) und schau ob dort Einträge für dieses Gerät drin sind, wenn ja, mit X entfernen.

@crunchip77  Schau auch Du mal obs ne Leiche gibt wie oben beschrieben.

**Comment by crunchip77** [comment]
@Pittini Bezug auf Leichen/doppelte Einträge, habe ich schon mittels script gepüft. Ich werde bei Gelegenheit mal alle Sensoren aus Raum und Funktion entfernen und nur einen einbinden. Mal sehen wie es dann aussieht.

**Comment by Pittini** [comment]
@crunchip77 Gute Idee, das wäre auch mein nächster Vorschlag gewesen.

**Comment by crunchip77** [comment]
@Pittini nun bin ich alles nochmal durchgegangen, alles Sensoren gelöscht und nur einen hinzugefügt, führte zum selbigen Fehler.
Nun hab ich nochmals die **Raum/Funktion Id`s** kontrolliert, da standen plötzlich "window" und "door" obwohl da nichts geändert wurde. Ursprünglich stand da "fenster" und "tuer", so wie auch im script schon immer hinterlegt.
Das habe ich nun wieder angepasst, Sensoren wieder eingepflegt, Alle Datenpunkte gelöscht und sämtliche Türen und Fenster einmal geöffnet und geschlossen, jedoch führt das bei Scriptstart nun zu folgenden Fehlern und komm nicht dahinter wo es noch hängt

PS: Die Sensoren sind per **alias** hinterlegt

`javascript.0	16:28:10.022	info	
Stopping script script.js.Benachrichtigung.FensterTür-Status
javascript.0	16:28:10.126	info	
Start JavaScript script.js.Benachrichtigung.FensterTür-Status (Javascript/js)
javascript.0	16:28:10.131	info	
starting Fensterskript, Version 1.6.15
javascript.0	16:28:10.132	info	
registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0	16:28:10.175	warn	
    at init (script.js.Benachrichtigung.FensterTür-Status:326:26)
javascript.0	16:28:10.175	warn	
    at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0	16:28:10.175	warn	
    at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0	16:28:10.175	warn	
    at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0	16:28:10.176	warn	
    at init (script.js.Benachrichtigung.FensterTür-Status:327:35)
javascript.0	16:28:10.176	warn	
    at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0	16:28:10.176	warn	
    at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0	16:28:10.176	warn	
    at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0	16:28:10.176	warn	
    at init (script.js.Benachrichtigung.FensterTür-Status:328:37)
javascript.0	16:28:10.176	warn	
    at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0	16:28:10.176	warn	
    at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0	16:28:10.176	warn	
    at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0	16:28:10.176	warn	
    at init (script.js.Benachrichtigung.FensterTür-Status:329:32)
javascript.0	16:28:10.176	warn	
    at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0	16:28:10.176	warn	
    at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0	16:28:10.176	warn	
    at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0	16:28:10.176	warn	
    at init (script.js.Benachrichtigung.FensterTür-Status:330:30)
javascript.0	16:28:10.177	warn	
    at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0	16:28:10.177	warn	
    at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0	16:28:10.177	warn	
    at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0	16:28:10.177	warn	
    at init (script.js.Benachrichtigung.FensterTür-Status:342:27)
javascript.0	16:28:10.177	warn	
    at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0	16:28:10.177	warn	
    at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0	16:28:10.177	warn	
    at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0	16:28:10.177	error	
    at CreateRoomsWithOpenDoorsList (script.js.Benachrichtigung.FensterTür-Status:867:45)
javascript.0	16:28:10.177	error	
    at main (script.js.Benachrichtigung.FensterTür-Status:352:5)
javascript.0	16:28:10.177	error	
    at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0	16:28:10.177	error	
    at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
`

**Comment by Pittini** [comment]
Ist jeder Sensor auch nem Raum zugeordnet? Wenn ja, mach mal im Script das Logging an und poste das Log vom Scriptstart bitte.

**Comment by fzoellne** [comment]
@Pittini habe alles dreimal geprüft, das gerät ist da nicht...

**Comment by Pittini** [comment]
@fzoellne Das Skript ist nicht in der Lage Geräte zu "erfinden". Irgendwoher muß das kommen.

**Comment by crunchip77** [comment]
@Pittini ja, Alle Sensoren sind korrekt eingebunden. Habe alles an logging aktiviert

`<html>
<body>

javascript.0 | 2025-03-27 19:21:16.955 | error | at createState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2987:34)
-- | -- | -- | --
javascript.0 | 2025-03-27 19:21:16.955 | error | at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0 | 2025-03-27 19:21:16.955 | error | at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0 | 2025-03-27 19:21:16.955 | error | at main (script.js.Benachrichtigung.FensterTür-Status:352:5)
javascript.0 | 2025-03-27 19:21:16.955 | error | at CreateRoomsWithOpenDoorsList (script.js.Benachrichtigung.FensterTür-Status:867:45)
javascript.0 | 2025-03-27 19:21:16.955 | error | Error in callback: TypeError: Cannot set properties of undefined (setting '1')
javascript.0 | 2025-03-27 19:21:16.953 | warn | at createState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2987:34)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at init (script.js.Benachrichtigung.FensterTür-Status:342:27)
javascript.0 | 2025-03-27 19:21:16.953 | warn | getState "javascript.0.Benachrichtigung.FensterTuerUeberwachung..VentWarnTime" not found (3)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at createState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2987:34)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at init (script.js.Benachrichtigung.FensterTür-Status:330:30)
javascript.0 | 2025-03-27 19:21:16.953 | warn | getState "javascript.0.Benachrichtigung.FensterTuerUeberwachung..SendDoorWarnMsg" not found (3)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at createState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2987:34)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0 | 2025-03-27 19:21:16.953 | warn | at init (script.js.Benachrichtigung.FensterTür-Status:329:32)
javascript.0 | 2025-03-27 19:21:16.952 | warn | getState "javascript.0.Benachrichtigung.FensterTuerUeberwachung..SendWindowWarnMsg" not found (3)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at createState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2987:34)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at init (script.js.Benachrichtigung.FensterTür-Status:328:37)
javascript.0 | 2025-03-27 19:21:16.952 | warn | getState "javascript.0.Benachrichtigung.FensterTuerUeberwachung..SendWindowOpenCloseMsg" not found (3)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at createState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2987:34)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at init (script.js.Benachrichtigung.FensterTür-Status:327:35)
javascript.0 | 2025-03-27 19:21:16.952 | warn | getState "javascript.0.Benachrichtigung.FensterTuerUeberwachung..SendDoorOpenCloseMsg" not found (3)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at createState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:2987:34)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at Object.<anonymous> (script.js.Benachrichtigung.FensterTür-Status:279:13)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at InitialSort (script.js.Benachrichtigung.FensterTür-Status:315:5)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at main (script.js.Benachrichtigung.FensterTür-Status:350:5)
javascript.0 | 2025-03-27 19:21:16.952 | warn | at init (script.js.Benachrichtigung.FensterTür-Status:326:26)
javascript.0 | 2025-03-27 19:21:16.952 | warn | getState "javascript.0.Benachrichtigung.FensterTuerUeberwachung..SendVentMsg" not found (3)
javascript.0 | 2025-03-27 19:21:16.952 | info | script.js.Benachrichtigung.FensterTür-Status: [ '' ]
javascript.0 | 2025-03-27 19:21:16.952 | info | script.js.Benachrichtigung.FensterTür-Status: []
javascript.0 | 2025-03-27 19:21:16.951 | info | script.js.Benachrichtigung.FensterTür-Status: []
javascript.0 | 2025-03-27 19:21:16.951 | info | script.js.Benachrichtigung.FensterTür-Status: [ '' ]
javascript.0 | 2025-03-27 19:21:16.951 | info | script.js.Benachrichtigung.FensterTür-Status: [ '' ]
javascript.0 | 2025-03-27 19:21:16.908 | info | script.js.Benachrichtigung.FensterTür-Status: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0 | 2025-03-27 19:21:16.908 | info | script.js.Benachrichtigung.FensterTür-Status: starting Fensterskript, Version 1.6.15
javascript.0 | 2025-03-27 19:21:16.902 | info | Start JavaScript script.js.Benachrichtigung.FensterTür-Status (Javascript/js)
javascript.0 | 2025-03-27 19:21:16.798 | info | Stopping script script.js.Benachrichtigung.FensterTür-Status


</body>
</html>`

**Comment by Pittini** [comment]
Entfern mal alle Sensoren. Füge dann einen Sensor direkt (nicht via alias) hinzu. Stell sicher dass der Raum gesetzt ist und die Funktion, und poste dann mal das Log. 
Hast Du discord und Headset, glaub das sollten wir mal per voice versuchen zu klären.

**Comment by crunchip77** [comment]
@Pittini erstmal danke fürs Angebot und die Zeit. Ich werde es morgen in aller Ruhe nochmal durchgehen. Wenn ich den Fehler nicht finde, komme ich gerne auf dein Angebot zurück.

Für mich ist nur unerklärlich, da ich noch anderweitig ein Fenster/Licht/Türen-Zähl script laufen habe und da jedoch alles funktioniert. Sprich Anzahl der Räume und Sensoren/Geräte werden da korrekt ausgegeben.

auch mit einem blockly funktioniert es,  siehe https://forum.iobroker.net/post/904083

**Comment by crunchip77** [comment]
@Pittini so, jetzt hab ich nochmal alles gelöscht, einen direkten zigbee Sensor eingebunden, immer noch gleiche Problem wie zu Beginn, siehe auch https://forum.iobroker.net/post/1187248, da hatte _schittl_ das selbe Problem.

und jetzt nochmal generell, bin etwas verwirrt
im Script ist hinterlegt
`const WhichWindowFunctionToUse = "Fenster"; // Legt fest nach welchem Begriff in Funktionen gesucht wird. Diese Funktion nur dem Datenpunkt zuweisen, NICHT dem ganzen Channel!
const WhichDoorFunctionToUse = "Tuer"; // Legt fest nach welchem Begriff in Funktionen gesucht wird. Diese Funktion nur dem Datenpunkt zuweisen, NICHT dem ganzen Channel!
const WindowIgnoreTime = 10000; // 10000 ms = 10 Sekunden - Zeit in ms für die kurzzeitiges öffnen/schliessen ignoriert wird
const DoorIgnoreTime = 1000; // 1000 ms = 1 Sekunden - Zeit in ms für die kurzzeitiges öffnen/schliessen ignoriert wird
const WhichEnumCategoryToUse = "functions"; // Legt fest in welcher Kategorie sich die Aufzählungen befinden! Nur ändern wer weis was er tut!
`

die Id Fenster ist klein geschrieben, im Script wird aber der **Name** also gross geschrieben, verlangt?

![Image](https://github.com/user-attachments/assets/989fc9a0-892e-4a2d-b31e-af8f677cbc88)

scriptlog
`<html>
<body>

javascript.0 | 2025-03-28 14:38:41.902 | error | at Script.runInContext (node:vm:149:12)
-- | -- | -- | --
javascript.0 | 2025-03-28 14:38:41.902 | error | at script.js.Benachrichtigung.FensterTür-Status:1468:3
javascript.0 | 2025-03-28 14:38:41.902 | error | at script.js.Benachrichtigung.FensterTür-Status:154:77
javascript.0 | 2025-03-28 14:38:41.902 | error | script.js.Benachrichtigung.FensterTür-Status: TypeError: Cannot read properties of undefined (reading '0')
javascript.0 | 2025-03-28 14:38:41.901 | error | script.js.Benachrichtigung.FensterTür-Status: getObject has been called with id of type "function" but expects a string
javascript.0 | 2025-03-28 14:38:41.900 | info | script.js.Benachrichtigung.FensterTür-Status: starting Fensterskript, Version 1.6.15
javascript.0 | 2025-03-28 14:38:41.898 | info | Start JavaScript script.js.Benachrichtigung.FensterTür-Status (Javascript/js)
javascript.0 | 2025-03-28 14:38:41.795 | info | Stopping script script.js.Benachrichtigung.FensterTür-Status


</body>
</html>`

**Comment by Pittini** [comment]
Zeig mal  bitte nen Screenshot wie der einzige eingebundene Sensor aussieht, so dass ich alles davon seh.

**Comment by crunchip77** [comment]
@Pittini 
habs mit nem Fenster und nem Tür Sensor probiert, jeweils einzeln und auch beide zusammen probiert. 

![Image](https://github.com/user-attachments/assets/ee172435-039a-4336-ae8a-86e14f39ac20)

![Image](https://github.com/user-attachments/assets/b8ab3e20-e86d-4927-ba87-2c1c5066c1a7)

Edit:
Ich habe auch mal die Funktion gelöscht und neu angelegt, jedoch bleibt es bei dem Fehler. 

@Pittini nun auch noch mal mit javascript auf stable zurück, Verhalten bleibt allerdings gleich

**Comment by crunchip77** [comment]
@Pittini hab jetzt viel hin und her probiert, bekomm es letztendlich aber nicht zum laufen. Hab dazu auch verschiedene KI Programme zu rate gezogen, Immer wieder Probleme beim Initialisieren, kein Sensor/kein Raum. Letztendlich hab ich mir nun mittels Perplexity ein eigenes Script gebaut. Macht was es soll ohne am iobroker etwas verändert zu haben, als Zusatz hab ich noch Tagesstatistiken der Öffnungszeiten und Zählerwerte für jeden einzelnen Tür/Fenster Sensor mit integriert. mal gucken was ich noch so mit Einbau.

**Comment by Pittini** [comment]
> [@Pittini](https://github.com/Pittini) hab jetzt viel hin und her probiert, bekomm es letztendlich aber nicht zum laufen. Hab dazu auch verschiedene KI Programme zu rate gezogen, Immer wieder Probleme beim Initialisieren, kein Sensor/kein Raum. Letztendlich hab ich mir nun mittels Perplexity ein eigenes Script gebaut. Macht was es soll ohne am iobroker etwas verändert zu haben, als Zusatz hab ich noch Tagesstatistiken der Öffnungszeiten und Zählerwerte für jeden einzelnen Tür/Fenster Sensor mit integriert. mal gucken was ich noch so mit Einbau.

Schön das Du ne Lösung für Dich gefunden hast. Ist echt nen kurioser Fehler bei Dir. Bei mir läuft das Skript nach wie vor einwandfrei, auch mit neuesten JS.
